config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "homes#top"
  # STUDY STARTpage
  get "start" => "homes#start", as: "start"

  resources :users, only:[:show,:edit,:update, :index] do
    resource :relationships, only:[:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end

  resources :targets, only:[:new,:create,:show,:edit,:update,:index, :destroy] do
    resources :target_comments, only:[:create,:destroy]
    resource :favorites, only:[:create,:destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  #association
  belongs_to :user
  belongs_to :target
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  #association
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/target.rb
class Target < ApplicationRecord

  #association
  belongs_to :user

  has_many :target_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  #validation
  with_options presence: true do
    validates :title, length: {maximum: 20}
    validates :description, length: {maximum: 150}
  end

  #userのfavoriteを判定
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/target_comment.rb
class TargetComment < ApplicationRecord

  #association
  belongs_to :user
  belongs_to :target

  #validation
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  #自分がフォローする側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  #自分がフォローした人の一覧をフォローされた人(followed)を参照して出力
  has_many :followings, through: :relationships, source: :followed

  #自分がフォローされる側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  #自分をフォローしている人の一覧をフォローした人(follower)を参照して出力
  has_many :followers, through: :reverse_of_relationships,source: :follower

  has_many :targets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :target_comments, dependent: :destroy
  has_many :time_stamps, dependent: :destroy

  validates :name, presence: true, length: {minimum: 2, maximum: 15}
  validates :introduction, length: {maximum: 50}

  has_one_attached :profile_image

  #画像を取得する処理
  def get_icon
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  #フォローする際の処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  #フォローを外す際の処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  #フォローしているかの判別
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  # サインイン後遷移画面

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  #サインアウト後遷移画面
  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    target = Target.find(params[:target_id])
    @favorite = current_user.favorites.new(target_id: target.id)
    @favorite.save
  end

  def destroy
    target = Target.find(params[:target_id])
    @favorite = current_user.favorites.find_by(target_id: target.id)
    @favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def study
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  #フォローする時
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  #フォローを外す時
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
  #自分をフォローしているUser一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
  #自分がフォローしているUser一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
end

app/controllers/target_comments_controller.rb
class TargetCommentsController < ApplicationController

  before_action :set_target

  def create
    @comment = TargetComment.new(target_comment_paraams)
    @comment.user_id = current_user.id
    @comment.target_id = @target.id
    @comment.save
  end

  def destroy
    @comment = TargetComment.find_by(id: params[:id], target_id: params[:target_id])
    @comment.destroy
  end

  private

  def target_comment_paraams
    params.require(:target_comment).permit(:comment)
  end

  def set_target
    @target = Target.find(params[:target_id])
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def new
    @target = Target.new
  end

  def create
    @target = Target.new(target_params)
    @target.user_id = current_user.id
    if @target.save
      redirect_to user_path(current_user), notice: "目標を登録しました"
    else
      render :new
    end
  end

  def index
    @targets = Target.all
  end

  def show
    @target = Target.find(params[:id])
    @comment = TargetComment.new
  end

  def edit
  end

  def update
    if @target.update(target_params)
      redirect_to user_path(current_user), notice: "更新しました"
    else
      render :edit
    end
  end

  def destroy
    if @target.destroy
      redirect_to user_path(@target.user), notice: "投稿は削除されました。"
    else
      @targets = Target.all
      render :index
    end

  end

  private

  def target_params
    params.require(:target).permit(:title, :description)
  end

  def ensure_correct_user
    @target = Target.find(params[:id])
    unless @target.user == current_user
      redirect_to root_path, alert: "不正なアクセスです"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
    @targets = Target.where(user_id: @user)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "更新が成功しました"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:profile_image, :introduction)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/target_comments_helper.rb
module TargetCommentsHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_btn.html.erb
<% if target.favorited_by?(current_user) %>
  <%= link_to target_favorites_path(target), method: :delete, remote: true, class: "text-decoration-none" do %>
    <i class="bi bi-heart-fill" aria-hidden = "true"></i>
    <%= target.favorites.count %>
  <% end %>
<% else %>
  <%= link_to target_favorites_path(target), method: :post, remote: true, class: "text-decoration-none" do %>
    <i class="bi bi-heart" aria-hidden = "true"></i>
    <%= target.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$(".favorite-btn").html("<%= j(render "favorites/btn", target: @favorite.target) %>")

app/views/favorites/destroy.js.erb
$(".favorite-btn").html("<%= j(render "favorites/btn", target: @favorite.target) %>")

app/views/homes/start.html.erb
<div class = "row p-3 d-flex justfiy-content-center mx-auto">
  <div class = "col-md-5 py-3 bg-body rounded shadow-sm ">
    <h1 class = "text-bold text-center">Study Start</h1>
    <hr />

    <!----- time select section ----->
    <div class = "time-select text-center">
      <h4 class = "text-bold">Time Select</h4>

      <button type = "button" class = "btn btn-secondary" data-time = "3600">60min</button>
      <button type = "button" class = "btn btn-secondary" data-time = "1800">30min</button>
      <button type = "button" class = "btn btn-secondary" data-time = "900">15min</button>
    </div>

    <hr />

    <!----- sound select section ----->
    <div class = "sound-select text-center">
      <h4 class = "text-bold">Sound Select</h4>

      <!-- cafe-btn-->
      <button type = "button" class = "btn btn-warning" data-sound = "<%= asset_path("cafe.mp3") %>" data-image = "<%= asset_path("cafe.jpg") %>" >
        <i class="bi bi-cup"></i><br />
        <h4>Cafe</h4>
      </button>

      <!-- rain-btn -->
      <button type = "button" class = "btn btn-warning" data-sound = "<%= asset_path("rain.mp3") %>" data-image = "<%= asset_path("rain.jpg") %>">
        <i class="bi bi-cloud-rain-heavy"></i><br />
        <h4>Rain</h4>
      </button>

      <!-- wave-btn -->
      <button type = "button" class = "btn btn-warning" data-sound = "<%= asset_path("wave.mp3") %>" data-image = "<%= asset_path("wave.jpg") %>">
        <i class="bi bi-droplet-half"></i><br />
        <h4>Wave</h4>
      </button>

      <!-- woods-btn -->
      <button type = "button" class = "btn btn-warning" data-sound = "<%= asset_path("bird.mp3") %>" data-image = "<%= asset_path("bird.jpg") %>">
        <i class="bi bi-tree"></i><br />
        <h4>Woods</h4>
      </button>
    </div>
    <div class = "text-center my-3">
      <!-- 再生ボタン -->
      <button id = "play" type = "button" class = "btn btn-lg btn-warning">
        <i>Play</i>
      </button>
    </div>

  </div>

  <!----- player content section ----->
  <div class = "player-container col-md-6 text-center rounded">

    <%= audio_tag("cafe.mp3", class: "sound rounded", loop: true) %>
    <%= image_tag("cafe.jpg", class: "back-ground") %>

    <!-- カウントスタートorストップ -->
    <h1 id = "time-display" class = "text-bold text-light">00:00</h1>
    <button id = "start-button" class = "btn btn-secondary">Start</button>
    <button id = "stop-button" class = "btn btn-secondary">Stop</button>

  </div>
</div>

app/views/homes/top.html.erb
<!----- main visual section ------>
<div class = "container-fluid main-visual">
  <div class = "row text-center ">
    <h1 class = "display-1 text-bold mb-4">Study,Start</h1>
    <h3 class = "mb-3 lh-1">学びを、始めよう</h3>
    <p class = "">
      自分が集中できる音を聞く。<br />
      自分の目標に打ち込む。
      そして、周りに共有する。
    </p>
  </div>
</div>

<!----- main section ----->
<div class = "container mt-1 pt-1">
  <h1 class = "text-center">About</h1>
  <hr />

  <!------  about 音を聴く  ------>

  <div class = "row d-flex justify-content-center">
    <div class = "col-md-5">
      <%= image_tag "listning.png", class: "img-fluid"%>
    </div>
    <div class = "col-md-5 text-center pt-5">

      <h1 class = "mb-3">音を聴く。</h1>

      <p class = "text-secondary lh-lg">
        自分が集中できる音を聞きながら、決まった時間勉強。<br />
        時間は15分・30分・60分から選べます。<br />
        自然音、雑音、生活音など<br />
        色々な音の中から、お好みの音を見つけて<br />
        自分が聴き心地の良い音を選びましょう。<br />

        おすすめはカフェの音です
      </p>
    </div>
  </div>
  <hr />
    <!------  about 勉強する  ------>
  <div class = "row d-flex justify-content-center mb-3 pb-2">
    <div class = "col-md-5">
      <%= image_tag "studying.png", class: "img-fluid"%>
    </div>
    <div class = "col-md-5 text-center pt-5">

      <h1 class = "mb-3">勉強する。</h1>

      <p class = "text-secondary lh-lg">
        集中できる音が見つかったら<br />
        勉強に取り掛かってみましょう。<br />
        雑音は、人間の集中力を高めてくれます。<br />
        あなたがなりたい自分になる為に<br />
        その目標に打ち込んでみましょう<br />
      </p>
    </div>
    <hr />
    <!------  about 共有する  ------>
    <div class = "row d-flex justify-content-center">
    <div class = "col-md-5">
      <%= image_tag "together.png", class: "img-fluid"%>
    </div>
    <div class = "col-md-5 text-center pt-5">

      <h1 class = "mb-3">共有する。</h1>

      <p class = "text-secondary lh-lg">
        一緒の目標を持つ仲間を見つけてみましょう。<br />
        それは、あなたが持つ不安を<br />
        解決に導くヒントになるかもしれません<br />
        気になったら、フォローしたり、<br />
        コメントしたりして<br />
        親交を深めていきましょう。
      </p>
    </div>

    <% if user_signed_in? %>
      <button type = "button" class = "btn btn-lg btn-secondary">
        <%= link_to "投稿してみる", new_target_path, class: "text-light"%>
      </button>
    <% else %>
      <button type = "button" class = "btn btn-lg btn-secondary">
        <%= link_to "始めてみる", new_user_registration_path, class: "text-light"%>
      </button>
    <% end %>

  </div>
</div>

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <div class = "text-danger">
    <h3><%= obj.errors.count %>件のエラーがあります</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stusta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <!-- googl font english-->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@500&display=swap" rel="stylesheet">
    <!-- google font japanese -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@500&display=swap" rel="stylesheet">
    <!-- bootstrap icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- javascript -->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <!------------header section-------------->
    <header class = "shadow-sm fixed-top">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a href="/" class = "navbar-brand fs-1">StuSta</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon light"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto">
              <% if user_signed_in? %>
                <li class = "nav-item">
                  <%= link_to "MY PAGE", user_path(current_user), class: "nav-link rounded" %>
                </li>
                <li class = "nav-item">
                  <%= link_to "USERS", users_path, class: "nav-link rounded" %>
                </li>
                <li class = "nav-item">
                  <%= link_to "TARGETS", targets_path, class: "nav-link rounded" %>
                </li>
                <li class = "nav-item">
                  <%= link_to "STUDY START", start_path, data: {"turbolinks"=>false}, class: "nav-link rounded" %>
                </li>
                <li class = "nav-item">
                  <%= link_to "LOG-OUT", destroy_user_session_path, method: :delete, class: "nav-link rounded" %>
                </li>
              <% else %>
                <li class = "nav-item">
                  <%= link_to "HOME", root_path, class: "nav-link rounded" %>
                </li>
                <li class = "nav-item">
                  <%= link_to "SIGN-UP", new_user_registration_path, class: "nav-link rounded" %>
                </li>
                <li class = "nav-item">
                  <%= link_to "LOG-IN", new_user_session_path, class: "nav-link rounded" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <!----- main section ----->
    <main>
      <% if flash[:notice] %>
          <div class="alert alert-success text-align-center" role="alert">
            <p id = "notice"><%= notice %></p>
          </div>
        <% end %>

        <%= yield %>
    </main>


    <!------------footer section----------->
    <footer class="container-fluid">
      <p class="text-lg"><a href="/" class = "text-light text-bold">StuSta</a></p>
      <p>&copy; 2022 Company, Inc.</p>
      <p>Ryuto.Motohashi</p>
    </footer>
  </body>
</html>

app/views/relationships/_btn.html.erb
<% if current_user.following?(user)%>
  <%= link_to user_relationships_path(user.id), method: :delete do %>
    <button type="button" class="btn btn-outline-warning">フォロー解除</button>
  <% end %>
<% else %>
  <%= link_to user_relationships_path(user.id), method: :post do %>
    <button type="button" class="btn btn-warning">フォロー</button>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<div class = "container py-5">
  <% if @users.exists? %>
      <table class="table">
        <thead>
          <tr>
            <th scope="col"><!--Userの写真--></th>
            <th scope="col">Name</th><!--Userの名前-->
            <th scope="col">Follows</th><!--Userのフォロー数-->
            <th scope="col">Followers</th><!--Userのフォロワー数-->
            <th scope="col"><!--フォローするボタン--></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= image_tag user.get_icon, size: "50x50", class: "mt-3 rounded-circle" %>
                <% end %>
              </td>
              <td><%= user.name %></td>
              <td><%= user.followings.count %></td>
              <td><%= user.followers.count %></td>
              <td><%= render "relationships/btn" , user: user %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
  <% else %>
    <h3 class = "text-bold text-center">No List</h3>
  <% end %>
</div>

app/views/relationships/followings.html.erb
<div class = "container py-5">
  <% if @users.exists? %>
      <table class="table">
        <thead>
          <tr>
            <th scope="col"><!--Userの写真--></th>
            <th scope="col">Name</th><!--Userの名前-->
            <th scope="col">Follows</th><!--Userのフォロー数-->
            <th scope="col">Followers</th><!--Userのフォロワー数-->
            <th scope="col"><!--フォローするボタン--></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= image_tag user.get_icon, size: "50x50", class: "mt-3 rounded-circle" %>
                <% end %>
              </td>
              <td><%= user.name %></td>
              <td><%= user.followings.count %></td>
              <td><%= user.followers.count %></td>
              <td><%= render "relationships/btn" , user: user %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
  <% else %>
    <h3 class = "text-bold text-center">No List</h3>
  <% end %>
</div>

app/views/target_comments/_comment_form.html.erb
<div>
  <%= form_with(model: [target, comment], local: false) do |f| %>
    <div class = "mb-3">
      <%= f.text_area :comment, rows: '5', placeholder: "コメントしてあげましょう", class: "form-control" %>
    </div>
    <div class = "mb-3">
      <%= f.submit "送信する", class: "btn btn-secondary btn-sm"%>
    </div>
  <% end %>
</div>

app/views/target_comments/_comment_index.html.erb
<% target.target_comments.each do |comment| %>
  <div class = "row border-bottom mb-2">
    <div class = "col-3 text-center mb-2">
      <%= link_to user_path(comment.user) do %>
        <%= image_tag comment.user.get_icon, size: "50x50", class: "mt-3 rounded-circle" %><br />
        <%= comment.user.name %><br />
      <% end %>
      <%= comment.created_at.strftime("%Y年%m月%d日 %H時%M分") %>
    </div>
    <div class = "col-7 border rounded mb-2">
      <%= comment.comment %>
    </div>
    <div class = "col-2 align-self-end mb-2">
      <% if comment.user == current_user %>
        <%= link_to target_target_comment_path(comment.target, comment), method: :delete, remote: true do %>
          <button type = "button" class = "btn btn-danger btn-sm">削除</button>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/target_comments/create.js.erb
$(".form-control").val("")
$(".target-comment-index").html("<%= j(render "target_comments/comment_index", target: @target) %>")

app/views/target_comments/destroy.js.erb
$(".target-comment-index").html("<%= j(render "target_comments/comment_index", target: @target) %>")

app/views/targets/_index.html.erb
<div class="my-3 p-3 bg-body rounded shadow-sm">
  <h2 class="border-bottom pb-2 mb-0 text-center">Posts List</h2>

  <!----- user投稿内容一覧表示 ----->

  <% targets.each do |target| %>
    <div class="d-flex pt-3">
      <%= image_tag target.user.get_icon, size: "80x80", class: "bd-placeholder-img flex-shrink-0 me-2 rounded" %>
      <div class = "row">
        <h4 class = ""><%= target.title %></h4>
        <p><%= target.description %></p>

        <%= target.created_at.strftime("%Y年%m月%d日 %H時%M分") %>

        コメント<%= target.target_comments.count %>件

        いいね<%= target.favorites.count %>

        <%= link_to target_path(target) do %>
          <button type = "button" class = "btn btn-secondary btn-sm">詳細</button>
        <% end %>
        <!----- もしログインユーザーなら削除機能表示 ----->
        <% if target.user == current_user %>
          <%= link_to target_path(target), method: :delete, data: { confirm: '削除しますか？' } do %>
            <button type = "button" class = "btn btn-warning btn-sm" >削除</button>
          <% end %>
        <% end %>
      </div>
    </div>
    <hr />
  <% end %>
</div>

app/views/targets/edit.html.erb
<div class = "container py-5">
  <%= render "layouts/error", obj: @target %>
  <div class = "row d-flex justify-content-center">
    <div class = "col-5">
      <h3>あなたの目標は?</h3>
        <%= form_with model: @target, method: :patch, local: true do |f| %>
          <div class = "mb-3">
            <%= f.label :title, "目標の題名", class: "form-label" %><br />
            <%= f.text_field :title, class: "form-control"%>
          </div>
          <div class = "mb-3">
            <%= f.label :description,"目標の詳細説明や質問", class: "form-label"%><br />
            <%= f.text_area :description, class: "form-control" %>
          </div>
          <div class = "mb-3">
            <%= f.submit "更新する" , class: "btn btn-warning"%>
            <%= link_to :back do %>
              <button type = "button" class = "btn btn-secondary ">戻る</button>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/targets/index.html.erb
<%= render "index", targets: @targets %>

app/views/targets/new.html.erb
<div class = "container py-5">
  <%= render "layouts/error", obj: @target %>
  <div class = "row d-flex justify-content-center">
    <div class = "col-5">
      <h3>あなたの目標は?</h3>
        <%= form_with model: @target, local: true do |f| %>
          <div class = "mb-3">
            <%= f.label :title, "目標の題名", class: "form-label" %><br />
            <%= f.text_field :title, placeholder: "目標を20文字以内で入力してください",class: "form-control"%>
          </div>
          <div class = "mb-3">
            <%= f.label :description, "目標の詳細説明や質問", class: "form-label"%><br />
            <%= f.text_area :description,  placeholder: "詳細な説明や質問を150文字以内で入力してください",class: "form-control" %>
          </div>
          <div class = "mb-3">
            <%= f.submit "目標を登録する" , class: "btn btn-warning"%>
            <%= link_to :back do %>
              <button type = "button" class = "btn btn-secondary ">戻る</button>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/targets/show.html.erb
<%= render "users/info", user: @target.user %>
<div class="my-3 mx-1 p-3 bg-body rounded shadow-sm">
  <div class="d-flex pt-3">
    <%= image_tag @target.user.get_icon, size: "80x80", class: "bd-placeholder-img flex-shrink-0 me-2 rounded" %>
    <div class = "row">
      <h4 class = ""><%= @target.title %></h4>
      <p><%= @target.description %></p>

      <%= @target.created_at.strftime("%Y年%m月%d日 %H時%M分") %>

      コメント<%= @target.target_comments.count %>件

    </div>
  </div>
    <% if @target.user == current_user %>
      <p>
        <%= link_to edit_target_path(@target) do %>
          <button type = "button" class = "btn btn-warning btn-sm">編集</button>
        <% end %>
      </p>
    <% end %>

    <div class = "favorite-btn">
      <%= render "favorites/btn", target: @target %>
    </div>
    <hr />

    <div class = "target-comment-index">
      <%= render "target_comments/comment_index", target: @target %>
    </div>
    <div>
      <%= render "target_comments/comment_form", target: @target, comment: @comment %>
    </div>
</div>

app/views/users/_info.html.erb
<div class="py-5 mx-1 text-center">
  <h2 class="display-5 fw-bold">User's Profile</h2>

  <!------- user profile ------->

  <!------- user icon ------->
  <%= image_tag user.get_icon, size: "200x200", class: "mt-3 rounded-circle d-block mx-auto mb-4" %>

  <!------- user name ------->
  <h1 class = "fs-2">name: <%= user.name %></h1>

  <!------- user introduction ------->
  <div class="col-lg-6 mx-auto">
    <p class = "mb-1">自己紹介</p>
    <p class="lead mb-4">
      <%= user.introduction %>
    </p>

  <div class = "d-grid gap-2 d-sm-flex justify-content-sm-center">

  <!------- user follower count ------->
    <div class ="followings-content mx-2">
      <p>フォロー数</p>
      <%= link_to user_followings_path(user) do %>
        <%= user.followings.count %>
      <% end %>
    </div>
  <!------- user following count ------->
    <div class ="followrs-content mx-2">
      <p>フォロワー数</p>
        <%= link_to user_followers_path(user) do %>
          <%= user.followers.count %>
        <% end %>
    </div>
  </div>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mt-2">
      <% if current_user != user  %>
        <%= render "relationships/btn", user: user %>
        <%= link_to user_path(user) do %>
          <button type = "button" class = "btn btn-light">UserPage</button>
        <% end %>
      <% else %>
        <%= link_to edit_user_path(user) do %>
          <button type = "button" class = "btn btn-secondary">編集</button>
        <% end %>
        <%= link_to new_target_path do %>
          <button type = "button" class = "btn btn-warning">投稿</button>
        <% end %>
      <% end %>
    </div>
    </div>
  </div>